### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Himadu2000**
1. **Changes**: Package Updates, Optimizing, (SI/TA) Language support.
2. **Required**: Even no other changes done, it's required to do a visual check for errors.
3. **Note**: webpack.config has been changed, required inspection.
4. **Updates**: Need to update Webpack with it's settings configuration.

### CODE REVIEW

**Comment by Himadu2000** [comment]
If complete pr cannot merge, copy the language files from them.

**Comment by LuBuss** [comment]
Can you please add the git precommit hook and run `npm run precommit` on current branch

**Comment by Himadu2000** [comment]
**No staged files found !**

**Comment by vamcart** [comment]
This PR has problem. cezerin-store2 not working fine after this PR.
Looks like we need to revert code

**Pull request merged**
