### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Himadu2000**

### CODE REVIEW

**Comment by capfsb** [comment]
is sass better than scss? I think its modification for modification. We have profit from this?

**Review by vamcart — COMMENTED** [review]
Why?!

What the reason of this change?!

**Comment by Himadu2000** [comment]
> is sass better than scss? I think its modification for modification. We have profit from this?

Well yeah sass is a modified version of scss, such no more pesky brackets and semicolons with some additional if you like to look into.

**Comment by capfsb** [comment]
Yes i know diferents between sass and scss, but i more like scss, brakets make more structure. In any case, this is simply a matter of taste and is not sufficient motivation to migrate to a particular technology.

**Comment by Himadu2000** [comment]
> Yes i know diferents between sass and scss, but i more like scss, brakets make more structure. In any case, this is simply a matter of taste and is not sufficient motivation to migrate to a particular technology.

Nobody told you to learn the difference, it's my opinion and I think many others would like it and if you want we can put a vote. And there's also a thing called over criticism rather than helping out with anything. But one main reason is duplicate code.

**Comment by capfsb** [comment]
This is no reason for change technology because "this more beautiful".
Sass does not help with code duplicate, you can also remove sass code for remove duplicates.
Yes maybe just put a vote

Also we need vote for
Changes NPM to Yarn
Changes Node+TSC to Deno

**Pull request closed without merging**
