### PR TITLE
Update attributeFilter.js

### PR DESCRIPTION
**Pull request by albertusgeyser**
Attributes Quantity - Feature Request #133

### CODE REVIEW

**Review by vamcart — APPROVED** [review]
attributeFilter.js  is ok.
But why you are adding autoPlay at this PR?!

**Comment by albertusgeyser** [comment]
Sorry still new to Github Pull Requests.

**Comment by vamcart** [comment]
> Sorry still new to Github Pull Requests.

Just add another commit to PR, remove changes to the homeSlider.js

**Comment by vamcart** [comment]
No.
Just back default code of homeSlider.js

**Comment by vamcart** [comment]
Added to the master code - https://github.com/Cezerin2/cezerin2-store/commit/928e60fcc7acb64cd58f0629f48f4becb1a9292b

**Comment by ngoyal16** [comment]
@vamcart why you didn't merge instead of doing manual change

**Comment by vamcart** [comment]
Because @albertusgeyser closed this PR, as you can see.

 albertusgeyser closed this 23 hours ago

**Comment by ngoyal16** [comment]
ok

**Pull request closed without merging**
