### PR TITLE
feature#143 add customer name to header

### PR DESCRIPTION
**Pull request by chrisrijos**
Customer name replaces default profile icon on login.
Adjusted mobile css to fit icons better on header.

### CODE REVIEW

**Review by vamcart — APPROVED** [review]
Tested. And it's working. But, imho, default account icon looks better. Maybe do not remove account icon and just add name at the left of the account icon whe user is logged in?!
Screenshot from 2019-06-17 23-19-56

**Comment by chrisrijos** [comment]
I'll update it with a nicer layout

**Review by ngoyal16 — APPROVED** [review]

**Review by LuBuss — CHANGES_REQUESTED** [review]
Agree with @vamcart we should not change icon. If adding name please ensure that mobile screens support this.

Alternate options:
- Add dropdown: show name and extra options (change address, order history, etc)

**Comment by chrisrijos** [comment]
Hey guys, the latest changes have been pushed up let me know what you guys think.

**Review by vamcart — APPROVED** [review]
Good.

But padding of the icon is not good.
And maybe make account button dropdown with bulma - https://bulma.io/documentation/components/dropdown/

Just for me - include materialui to the theme just for 1 dropdown - it's not good solution.

Screenshot from 2019-06-18 23-46-23
Screenshot from 2019-06-18 23-46-27

**Review by LuBuss — APPROVED** [review]
Agree with Alex that Material-UI might be a little overkill just for a single component. 

Do you think/plan to update other components to material UI?
css could have some minor improvements:
- dropdown could be under icon

**Comment by chrisrijos** [comment]
The reason i added material was because we already use material forms and the app is overly material styled. So we should drive the rest of the UI forward with material components to keep it simple.

**Pull request merged**
