### PR TITLE
Fixed reference path failed when npm run build

### PR DESCRIPTION
**Pull request by srihamat**
I found error when running npm run build that can not found ../../../config/store path, by look at the path file it's at 
cezerin2-store/node_modules/theme/dist/components/homeSlider.js
cezerin2-store/node_modules/theme/dist/components/footer.js

Basically, it need ../../../../config/store

Which after changing this file then call `npm i --save ./theme` again then no problem found.
Note: I face error when run `npm i`

Ref: [Steps to reproduce](https://medium.com/@srihamat.a/ubuntu-18-04-how-to-install-cezerin-6067f409e0c)

### CODE REVIEW

**Review by vamcart — COMMENTED** [review]
For me, default cezerin2-store is builded correctly on my local ubuntu machine.

But with your changes from PR - i have this error through build:

ERROR in ./theme/dist/components/homeSlider.js
Module not found: Error: Can't resolve '../../../../config/store' in '/home/work/My/1/cezerin2/cezerin2-store/theme/dist/components'
 @ ./theme/dist/components/homeSlider.js 23:13-48
 @ ./theme/dist/containers/index.js
 @ ./theme/dist/index.js
 @ multi theme

ERROR in ./theme/dist/components/footer.js
Module not found: Error: Can't resolve '../../../../config/store' in '/home/work/My/1/cezerin2/cezerin2-store/theme/dist/components'
 @ ./theme/dist/components/footer.js 21:13-48
 @ ./theme/dist/containers/shared.js
 @ ./theme/dist/index.js
 @ multi theme

**Comment by srihamat** [comment]
@vamcart Many thanks for response.

The reason I make this change is my students want to work on cezerin2 as a personal project with his/her fresh installed Ubuntu then they face the errors. I try out on error to make it work then give them the steps. I remember after that they show me particular steps really work for them. I'm not sure what is the difference between your environment and fresh installed Ubuntu environment.

Let's discuss on, how to make people easily build and run it ?
I'm willing to help if needed.

**Comment by vamcart** [comment]
Very strange.
I have ubuntu too on my local pc.
Test it on ubunto 16.04, ubuntu 18.04, digitalocean uburntu 16.04, digitalocean ubuntu 18.04.

Builded fine by default.
And not builded with your changes.

My nodejs and pm version is:
vam@vam:~$ node -v
v11.0.0
vam@vam:~$ npm -v
6.4.1
vam@vam:~$

**Comment by vamcart** [comment]
Looks like this problem already resolved in the master code.

**Pull request closed without merging**
