### PR TITLE
Update PayPalCheckout.js

### PR DESCRIPTION
**Pull request by thienpow**
checkout.js is deprecated. replaced with new paypal sdk.

### CODE REVIEW

**Comment by neunygph** [comment]
Is there a confirmation step on this? I don’t see any confirmation button from the new changes.

**Comment by thienpow** [comment]
> Is there a confirmation step on this? I don’t see any confirmation button from the new changes.

it's handled by the new sdk as it require to capture the approval instead of calling authenticate function in previous checkout.js so now it doesn't have the worry of onError or onCancel, as the new sdk do not expose such function to let developer to handle.

**Comment by neunygph** [comment]
No I’m talking about the confirmation step that let end-users confirm the payment. If you notice, when you buy something online and pay with PayPal you will be asked to login with your PayPal account to verify payment method. When done, end user will be redirected to the check out site again to confirm the payment. Without this step, the payment will be processed automatically without letting users the option to cancel or confirm a purchase.

**Comment by neunygph** [comment]
Even with the new SDK, they should have this step.

**Comment by thienpow** [comment]
u can test it. they removed the requirement for confirmation

**Comment by neunygph** [comment]
You should be able to enable confirmation step with this https://developer.paypal.com/docs/checkout/integration-features/confirmation-page/

**Comment by neunygph** [comment]
You can just replace the checkout.js url with the new PayPal sdk url, the implementation should be almost identical. It was built based on the old SDK.

**Comment by thienpow** [comment]
u can test it, the confirmation is optional, it can be more straight forward, if we enable the confirmation, it will be double confirm already.  cant just replace the url, the naming are different.

**Comment by vamcart** [comment]
How to complete order at the store with paypal method selected?!
and how to see this order at store admin (dashboard)

Place order button not showing up.

**Comment by LuBuss** [comment]
Though Paypal confirmation is optional every PayPal flow document shows a confirmation page, Considering we had this functionality, I dont think we should remove it. Can we implement the new SDK with the confirmation option

**Comment by neunygph** [comment]
I agree, I don’t think we should remove this feature. Customers’ satisfaction is the first priority, therefore we should leave them with all possible options. We rather make it one step slower rather to confuse end-users.

**Comment by neunygph** [comment]
@thienpow , what you are doing with the pull request is what we had in the past ( only different syntax). We removed it and added the confirmation step to support better users options.

**Pull request closed without merging**
