### PR TITLE
Added MetaTags to customer account page

### PR DESCRIPTION
**Pull request by kayhanb**
Metas was not working on account page

### CODE REVIEW

**Review by vamcart — APPROVED** [review]

**Comment by lortschi** [comment]
Why we need this? Account page shouldn‘t be tracked by searchmachines. It containes sensible personal data.

**Comment by vamcart** [comment]
Why not? Meta title "must have", imho.

**Comment by lortschi** [comment]
ok but what is the benefit of get privacy data tracked by searchmachines? It‘s for me a privacy risk if data of customers get indexed by searchmachines.

**Comment by lortschi** [comment]
But what purpose or benefit is by this meta if you want here to allow and in the robot.txt disallow? :) You also set here canonical links to force organic search to be crawled by the robots. 
Please read also this to understand how SEO works: https://www.searchenginejournal.com/robots-txt-security-risks/289719/#close
I have a SEO certification and doing SEO and SEA by my work: https://marc-o-polo.com
Sry I can not this code accept for good.

**Pull request merged**
